--[[
    fsg_cooking — ox_inventory item definitions
    Add these entries to ox_inventory/data/items.lua
    inside the return { } table.
--]]

-- ─────────────────────────────────────────────────────────────────────────────
-- APPLIANCES  (placeable props — used as inventory items to deploy)
-- ─────────────────────────────────────────────────────────────────────────────
['fsg_bbq_grill'] = {
    label  = 'BBQ Grill',
    weight = 5000,
    stack  = false,
    close  = true,
    description = 'A portable BBQ grill. Place it to start cooking.',
},
['fsg_brewer'] = {
    label  = 'Coffee Brewer',
    weight = 3000,
    stack  = false,
    close  = true,
    description = 'A countertop coffee brewer.',
},
['fsg_fryer'] = {
    label  = 'Deep Fryer',
    weight = 4000,
    stack  = false,
    close  = true,
    description = 'A deep fryer for frying food.',
},
['fsg_griddle'] = {
    label  = 'Griddle',
    weight = 3500,
    stack  = false,
    close  = true,
    description = 'A flat-top griddle for cooking.',
},
['fsg_juicer'] = {
    label  = 'Juicer',
    weight = 2000,
    stack  = false,
    close  = true,
    description = 'An electric juicer for making fresh juice.',
},
['fsg_microwave'] = {
    label  = 'Microwave',
    weight = 4500,
    stack  = false,
    close  = true,
    description = 'A microwave oven.',
},
['fsg_pizza_oven'] = {
    label  = 'Pizza Oven',
    weight = 8000,
    stack  = false,
    close  = true,
    description = 'A stone pizza oven.',
},
['fsg_processor'] = {
    label  = 'Food Processor',
    weight = 2500,
    stack  = false,
    close  = true,
    description = 'A food processor for blending and chopping.',
},
['fsg_stove'] = {
    label  = 'Portable Stove',
    weight = 5000,
    stack  = false,
    close  = true,
    description = 'A portable gas stove.',
},
['fsg_toaster'] = {
    label  = 'Toaster',
    weight = 1500,
    stack  = false,
    close  = true,
    description = 'A pop-up toaster.',
},

-- ─────────────────────────────────────────────────────────────────────────────
-- DECORATION PROPS
-- ─────────────────────────────────────────────────────────────────────────────
['fsg_deco_chair_bbq'] = {
    label  = 'BBQ Chair',
    weight = 2000,
    stack  = false,
    close  = true,
    description = 'A folding chair for outdoor BBQs.',
},
['fsg_deco_cooler'] = {
    label  = 'Cooler',
    weight = 3000,
    stack  = false,
    close  = true,
    description = 'An ice cooler to keep drinks cold.',
},
['fsg_deco_table_wood'] = {
    label  = 'Wooden Table',
    weight = 4000,
    stack  = false,
    close  = true,
    description = 'A folding wooden table.',
},

-- ─────────────────────────────────────────────────────────────────────────────
-- RAW MEATS / SEAFOOD
-- ─────────────────────────────────────────────────────────────────────────────
['fsg_bacon'] = {
    label  = 'Bacon',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'Raw bacon strips.',
},
['fsg_chicken_breast'] = {
    label  = 'Chicken Breast',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'A raw chicken breast.',
},
['fsg_chicken_wings'] = {
    label  = 'Chicken Wings',
    weight = 250,
    stack  = true,
    close  = true,
    description = 'Raw chicken wings.',
},
['fsg_ham'] = {
    label  = 'Ham',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'A whole ham.',
},
['fsg_hamslice'] = {
    label  = 'Ham Slice',
    weight = 150,
    stack  = true,
    close  = true,
    description = 'A slice of ham.',
},
['fsg_pork_ribs'] = {
    label  = 'Pork Ribs',
    weight = 600,
    stack  = true,
    close  = true,
    description = 'A rack of pork ribs.',
},
['fsg_pork_shoulder'] = {
    label  = 'Pork Shoulder',
    weight = 800,
    stack  = true,
    close  = true,
    description = 'A raw pork shoulder.',
},
['fsg_raw_beef'] = {
    label  = 'Raw Beef',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'Raw ground beef.',
},
['fsg_raw_chicken'] = {
    label  = 'Raw Chicken',
    weight = 350,
    stack  = true,
    close  = true,
    description = 'A raw whole chicken.',
},
['fsg_raw_fish'] = {
    label  = 'Raw Fish',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'A raw fish fillet.',
},
['fsg_raw_salmon'] = {
    label  = 'Raw Salmon',
    weight = 350,
    stack  = true,
    close  = true,
    description = 'A raw salmon fillet.',
},
['fsg_raw_sausages'] = {
    label  = 'Raw Sausages',
    weight = 250,
    stack  = true,
    close  = true,
    description = 'A pack of raw sausages.',
},
['fsg_raw_shrimp'] = {
    label  = 'Raw Shrimp',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'A pack of raw shrimp.',
},
['fsg_raw_steak'] = {
    label  = 'Raw Steak',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'A thick raw steak.',
},
['fsg_squid'] = {
    label  = 'Squid',
    weight = 250,
    stack  = true,
    close  = true,
    description = 'Fresh squid.',
},
['fsg_pepperoni'] = {
    label  = 'Pepperoni',
    weight = 150,
    stack  = true,
    close  = true,
    description = 'Sliced pepperoni.',
},

-- ─────────────────────────────────────────────────────────────────────────────
-- FRUITS
-- ─────────────────────────────────────────────────────────────────────────────
['fsg_apple'] = {
    label  = 'Apple',
    weight = 150,
    stack  = true,
    close  = true,
    description = 'A fresh apple.',
},
['fsg_banana'] = {
    label  = 'Banana',
    weight = 100,
    stack  = true,
    close  = true,
    description = 'A ripe banana.',
},
['fsg_grapes'] = {
    label  = 'Grapes',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'A bunch of grapes.',
},
['fsg_lemon'] = {
    label  = 'Lemon',
    weight = 100,
    stack  = true,
    close  = true,
    description = 'A fresh lemon.',
},
['fsg_orange'] = {
    label  = 'Orange',
    weight = 150,
    stack  = true,
    close  = true,
    description = 'A fresh orange.',
},
['fsg_pineapple'] = {
    label  = 'Pineapple',
    weight = 500,
    stack  = true,
    close  = true,
    description = 'A whole pineapple.',
},
['fsg_strawberry'] = {
    label  = 'Strawberry',
    weight = 50,
    stack  = true,
    close  = true,
    description = 'Fresh strawberries.',
},
['fsg_watermelon'] = {
    label  = 'Watermelon',
    weight = 800,
    stack  = true,
    close  = true,
    description = 'A whole watermelon.',
},

-- ─────────────────────────────────────────────────────────────────────────────
-- VEGETABLES
-- ─────────────────────────────────────────────────────────────────────────────
['fsg_beet'] = {
    label  = 'Beetroot',
    weight = 150,
    stack  = true,
    close  = true,
    description = 'A fresh beetroot.',
},
['fsg_bell_pepper'] = {
    label  = 'Bell Pepper',
    weight = 120,
    stack  = true,
    close  = true,
    description = 'A fresh bell pepper.',
},
['fsg_carrot'] = {
    label  = 'Carrot',
    weight = 100,
    stack  = true,
    close  = true,
    description = 'A fresh carrot.',
},
['fsg_celery'] = {
    label  = 'Celery',
    weight = 100,
    stack  = true,
    close  = true,
    description = 'A stick of celery.',
},
['fsg_corn'] = {
    label  = 'Corn',
    weight = 150,
    stack  = true,
    close  = true,
    description = 'An ear of corn.',
},
['fsg_eggplant'] = {
    label  = 'Eggplant',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'A fresh eggplant.',
},
['fsg_garlic'] = {
    label  = 'Garlic',
    weight = 50,
    stack  = true,
    close  = true,
    description = 'A bulb of garlic.',
},
['fsg_herbs'] = {
    label  = 'Fresh Herbs',
    weight = 50,
    stack  = true,
    close  = true,
    description = 'A bundle of fresh herbs.',
},
['fsg_mushroom'] = {
    label  = 'Mushroom',
    weight = 80,
    stack  = true,
    close  = true,
    description = 'Fresh mushrooms.',
},
['fsg_okra'] = {
    label  = 'Okra',
    weight = 80,
    stack  = true,
    close  = true,
    description = 'Fresh okra.',
},
['fsg_onion'] = {
    label  = 'Onion',
    weight = 120,
    stack  = true,
    close  = true,
    description = 'A fresh onion.',
},
['fsg_potato'] = {
    label  = 'Potato',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'A fresh potato.',
},
['fsg_tomato'] = {
    label  = 'Tomato',
    weight = 120,
    stack  = true,
    close  = true,
    description = 'A fresh tomato.',
},
['fsg_vegetables'] = {
    label  = 'Mixed Vegetables',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'A bag of mixed vegetables.',
},
['fsg_zucchini'] = {
    label  = 'Zucchini',
    weight = 150,
    stack  = true,
    close  = true,
    description = 'A fresh zucchini.',
},

-- ─────────────────────────────────────────────────────────────────────────────
-- DAIRY / EGGS
-- ─────────────────────────────────────────────────────────────────────────────
['fsg_butter'] = {
    label  = 'Butter',
    weight = 100,
    stack  = true,
    close  = true,
    description = 'A block of butter.',
},
['fsg_cheese'] = {
    label  = 'Cheese',
    weight = 150,
    stack  = true,
    close  = true,
    description = 'A block of cheese.',
},
['fsg_cheese_curds'] = {
    label  = 'Cheese Curds',
    weight = 150,
    stack  = true,
    close  = true,
    description = 'Fresh cheese curds.',
},
['fsg_cream'] = {
    label  = 'Cream',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'A carton of cream.',
},
['fsg_egg'] = {
    label  = 'Egg',
    weight = 60,
    stack  = true,
    close  = true,
    description = 'A fresh egg.',
},
['fsg_milk'] = {
    label  = 'Milk',
    weight = 500,
    stack  = true,
    close  = true,
    description = 'A bottle of fresh milk.',
},
['fsg_mozzarella'] = {
    label  = 'Mozzarella',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'A ball of fresh mozzarella.',
},

-- ─────────────────────────────────────────────────────────────────────────────
-- GRAINS / BREAD
-- ─────────────────────────────────────────────────────────────────────────────
['fsg_bread'] = {
    label  = 'Bread',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'A loaf of bread.',
},
['fsg_bread_slice'] = {
    label  = 'Bread Slice',
    weight = 50,
    stack  = true,
    close  = true,
    description = 'A single slice of bread.',
},
['fsg_breadcrumbs'] = {
    label  = 'Breadcrumbs',
    weight = 100,
    stack  = true,
    close  = true,
    description = 'A bag of breadcrumbs.',
},
['fsg_burger_bun'] = {
    label  = 'Burger Bun',
    weight = 100,
    stack  = true,
    close  = true,
    description = 'A soft burger bun.',
},
['fsg_cornmeal'] = {
    label  = 'Cornmeal',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'A bag of cornmeal.',
},
['fsg_flour'] = {
    label  = 'Flour',
    weight = 500,
    stack  = true,
    close  = true,
    description = 'A bag of flour.',
},
['fsg_macaroni'] = {
    label  = 'Macaroni',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'Dry macaroni pasta.',
},
['fsg_oatmeal'] = {
    label  = 'Oatmeal',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'A bag of rolled oats.',
},
['fsg_pasta'] = {
    label  = 'Pasta',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'Dry pasta.',
},
['fsg_pizza_dough'] = {
    label  = 'Pizza Dough',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'Prepared pizza dough.',
},
['fsg_ramen_noodles'] = {
    label  = 'Ramen Noodles',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'Dry ramen noodles.',
},
['fsg_rice'] = {
    label  = 'Rice',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'A bag of white rice.',
},
['fsg_spring_roll_wrapper'] = {
    label  = 'Spring Roll Wrappers',
    weight = 100,
    stack  = true,
    close  = true,
    description = 'Rice paper spring roll wrappers.',
},
['fsg_tortilla'] = {
    label  = 'Tortilla',
    weight = 100,
    stack  = true,
    close  = true,
    description = 'Flour tortillas.',
},

-- ─────────────────────────────────────────────────────────────────────────────
-- SAUCES / CONDIMENTS / SEASONINGS
-- ─────────────────────────────────────────────────────────────────────────────
['fsg_bbq_sauce'] = {
    label  = 'BBQ Sauce',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'A bottle of smoky BBQ sauce.',
},
['fsg_chicken_stock'] = {
    label  = 'Chicken Stock',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'A carton of chicken stock.',
},
['fsg_coconut_milk'] = {
    label  = 'Coconut Milk',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'A can of coconut milk.',
},
['fsg_curry_paste'] = {
    label  = 'Curry Paste',
    weight = 150,
    stack  = true,
    close  = true,
    description = 'A jar of curry paste.',
},
['fsg_oil'] = {
    label  = 'Cooking Oil',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'A bottle of cooking oil.',
},
['fsg_pepper'] = {
    label  = 'Pepper',
    weight = 50,
    stack  = true,
    close  = true,
    description = 'Ground black pepper.',
},
['fsg_pesto_sauce'] = {
    label  = 'Pesto Sauce',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'A jar of basil pesto.',
},
['fsg_salt'] = {
    label  = 'Salt',
    weight = 50,
    stack  = true,
    close  = true,
    description = 'Table salt.',
},
['fsg_soy_sauce'] = {
    label  = 'Soy Sauce',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'A bottle of soy sauce.',
},
['fsg_syrup'] = {
    label  = 'Maple Syrup',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'A bottle of maple syrup.',
},
['fsg_tomato_sauce'] = {
    label  = 'Tomato Sauce',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'A jar of tomato sauce.',
},

-- ─────────────────────────────────────────────────────────────────────────────
-- BAKING / DESSERT INGREDIENTS
-- ─────────────────────────────────────────────────────────────────────────────
['fsg_cake_mix'] = {
    label  = 'Cake Mix',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'A box of cake mix.',
},
['fsg_chocolate'] = {
    label  = 'Chocolate',
    weight = 100,
    stack  = true,
    close  = true,
    description = 'A bar of cooking chocolate.',
},
['fsg_cinnamon'] = {
    label  = 'Cinnamon',
    weight = 50,
    stack  = true,
    close  = true,
    description = 'Ground cinnamon.',
},
['fsg_cocoapod'] = {
    label  = 'Cocoa Pod',
    weight = 150,
    stack  = true,
    close  = true,
    description = 'A fresh cocoa pod.',
},
['fsg_pie_crust'] = {
    label  = 'Pie Crust',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'A pre-made pie crust.',
},
['fsg_pancake_mix'] = {
    label  = 'Pancake Mix',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'A box of pancake mix.',
},
['fsg_pudding'] = {
    label  = 'Pudding Mix',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'A box of pudding mix.',
},
['fsg_sugar'] = {
    label  = 'Sugar',
    weight = 500,
    stack  = true,
    close  = true,
    description = 'A bag of white sugar.',
},
['fsg_vanilla'] = {
    label  = 'Vanilla Extract',
    weight = 100,
    stack  = true,
    close  = true,
    description = 'A bottle of vanilla extract.',
},
['fsg_vaniwafers'] = {
    label  = 'Vanilla Wafers',
    weight = 150,
    stack  = true,
    close  = true,
    description = 'A pack of vanilla wafers.',
},

-- ─────────────────────────────────────────────────────────────────────────────
-- PACKAGED / STORE GOODS
-- ─────────────────────────────────────────────────────────────────────────────
['fsg_berrycream'] = {
    label  = 'Berry Cream',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'Berry-flavoured cream.',
},
['fsg_choccream'] = {
    label  = 'Chocolate Cream',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'Chocolate-flavoured cream.',
},
['fsg_coffee_beans'] = {
    label  = 'Coffee Beans',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'A bag of roasted coffee beans.',
},
['fsg_frozen_dinner'] = {
    label  = 'Frozen Dinner',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'A microwaveable frozen dinner.',
},
['fsg_frozewaff'] = {
    label  = 'Frozen Waffles',
    weight = 250,
    stack  = true,
    close  = true,
    description = 'A box of frozen waffles.',
},
['fsg_ice'] = {
    label  = 'Ice',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'A bag of ice cubes.',
},
['fsg_popcorn_bag'] = {
    label  = 'Popcorn Bag',
    weight = 150,
    stack  = true,
    close  = true,
    description = 'An unpopped microwave popcorn bag.',
},
['fsg_soup_mix'] = {
    label  = 'Soup Mix',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'A packet of dried soup mix.',
},
['fsg_toasti'] = {
    label  = 'Toastie',
    weight = 150,
    stack  = true,
    close  = true,
    description = 'A packaged toastie.',
},
['fsg_water'] = {
    label  = 'Water',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'A bottle of water.',
},
['fsg_applejuice'] = {
    label  = 'Apple Juice',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'A carton of apple juice.',
},

-- ─────────────────────────────────────────────────────────────────────────────
-- COOKED / CRAFTED RESULTS
-- ─────────────────────────────────────────────────────────────────────────────
['fsg_apple_juice'] = {
    label  = 'Fresh Apple Juice',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'Freshly squeezed apple juice.',
},
['fsg_applesauce'] = {
    label  = 'Applesauce',
    weight = 250,
    stack  = true,
    close  = true,
    description = 'Homemade applesauce.',
},
['fsg_baked_potato'] = {
    label  = 'Baked Potato',
    weight = 250,
    stack  = true,
    close  = true,
    description = 'A fluffy baked potato.',
},
['fsg_bbq_burger'] = {
    label  = 'BBQ Burger',
    weight = 350,
    stack  = true,
    close  = true,
    description = 'A juicy BBQ burger.',
},
['fsg_bbq_chicken'] = {
    label  = 'BBQ Chicken',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'Grilled BBQ chicken.',
},
['fsg_bbq_ribs'] = {
    label  = 'BBQ Ribs',
    weight = 600,
    stack  = true,
    close  = true,
    description = 'Slow-cooked BBQ pork ribs.',
},
['fsg_bbq_sausages'] = {
    label  = 'BBQ Sausages',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'Grilled BBQ sausages.',
},
['fsg_beet_juice'] = {
    label  = 'Beet Juice',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'Freshly pressed beet juice.',
},
['fsg_bffriedrice'] = {
    label  = 'Beef Fried Rice',
    weight = 450,
    stack  = true,
    close  = true,
    description = 'Wok-fried rice with beef.',
},
['fsg_bpudding'] = {
    label  = 'Banana Pudding',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'Creamy banana pudding.',
},
['fsg_bstirfry'] = {
    label  = 'Beef Stir Fry',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'Stir-fried beef with vegetables.',
},
['fsg_burnt_food'] = {
    label  = 'Burnt Food',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'Completely burnt food. Not very appetising.',
},
['fsg_carrot_juice'] = {
    label  = 'Carrot Juice',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'Freshly pressed carrot juice.',
},
['fsg_celery_juice'] = {
    label  = 'Celery Juice',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'Freshly pressed celery juice.',
},
['fsg_chicken_nuggets'] = {
    label  = 'Chicken Nuggets',
    weight = 250,
    stack  = true,
    close  = true,
    description = 'Crispy fried chicken nuggets.',
},
['fsg_chicken_pesto_pizza'] = {
    label  = 'Chicken Pesto Pizza',
    weight = 500,
    stack  = true,
    close  = true,
    description = 'Wood-fired pizza with chicken and pesto.',
},
['fsg_chickensand'] = {
    label  = 'Chicken Sandwich',
    weight = 350,
    stack  = true,
    close  = true,
    description = 'A crispy chicken sandwich.',
},
['fsg_ckfriedrice'] = {
    label  = 'Chicken Fried Rice',
    weight = 450,
    stack  = true,
    close  = true,
    description = 'Wok-fried rice with chicken.',
},
['fsg_cooked_oatmeal'] = {
    label  = 'Cooked Oatmeal',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'A warm bowl of oatmeal.',
},
['fsg_cooked_steak'] = {
    label  = 'Cooked Steak',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'A perfectly cooked steak.',
},
['fsg_crepes'] = {
    label  = 'Crepes',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'Thin French crepes.',
},
['fsg_curry'] = {
    label  = 'Curry',
    weight = 500,
    stack  = true,
    close  = true,
    description = 'A rich aromatic curry.',
},
['fsg_fancy_steak'] = {
    label  = 'Fancy Steak',
    weight = 450,
    stack  = true,
    close  = true,
    description = 'A premium restaurant-quality steak.',
},
['fsg_fish_and_chips'] = {
    label  = 'Fish and Chips',
    weight = 500,
    stack  = true,
    close  = true,
    description = 'Classic battered fish with chips.',
},
['fsg_fried_calamari'] = {
    label  = 'Fried Calamari',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'Golden fried calamari rings.',
},
['fsg_fried_cheese_curds'] = {
    label  = 'Fried Cheese Curds',
    weight = 250,
    stack  = true,
    close  = true,
    description = 'Deep-fried cheese curds.',
},
['fsg_fried_chicken_wings'] = {
    label  = 'Fried Chicken Wings',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'Crispy fried chicken wings.',
},
['fsg_fried_okra'] = {
    label  = 'Fried Okra',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'Southern fried okra.',
},
['fsg_fried_rice'] = {
    label  = 'Fried Rice',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'Classic fried rice.',
},
['fsg_fried_shrimp'] = {
    label  = 'Fried Shrimp',
    weight = 250,
    stack  = true,
    close  = true,
    description = 'Crispy fried shrimp.',
},
['fsg_grape_juice'] = {
    label  = 'Grape Juice',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'Freshly pressed grape juice.',
},
['fsg_grilled_corn'] = {
    label  = 'Grilled Corn',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'Char-grilled corn on the cob.',
},
['fsg_grilled_fish'] = {
    label  = 'Grilled Fish',
    weight = 350,
    stack  = true,
    close  = true,
    description = 'Perfectly grilled fish.',
},
['fsg_grilled_shrimp'] = {
    label  = 'Grilled Shrimp',
    weight = 250,
    stack  = true,
    close  = true,
    description = 'Char-grilled shrimp.',
},
['fsg_grilled_vegetables'] = {
    label  = 'Grilled Vegetables',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'Mixed grilled vegetables.',
},
['fsg_hamtoastie'] = {
    label  = 'Ham Toastie',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'A toasted ham sandwich.',
},
['fsg_homemade_soup'] = {
    label  = 'Homemade Soup',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'A hearty homemade soup.',
},
['fsg_hot_chocolate'] = {
    label  = 'Hot Chocolate',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'A warm mug of hot chocolate.',
},
['fsg_meatlovers_pizza'] = {
    label  = "Meat Lover's Pizza",
    weight = 600,
    stack  = true,
    close  = true,
    description = "Wood-fired meat lover's pizza.",
},
['fsg_microwave_chocolate_mug_cake'] = {
    label  = 'Chocolate Mug Cake',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'A quick microwave chocolate mug cake.',
},
['fsg_microwave_mac_cheese'] = {
    label  = 'Mac & Cheese',
    weight = 350,
    stack  = true,
    close  = true,
    description = 'Microwaved macaroni and cheese.',
},
['fsg_mozzarella_sticks'] = {
    label  = 'Mozzarella Sticks',
    weight = 250,
    stack  = true,
    close  = true,
    description = 'Deep-fried mozzarella sticks.',
},
['fsg_nanacream'] = {
    label  = 'Banana Cream',
    weight = 250,
    stack  = true,
    close  = true,
    description = 'Banana-flavoured cream dessert.',
},
['fsg_omelette'] = {
    label  = 'Omelette',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'A fluffy omelette.',
},
['fsg_onion_rings'] = {
    label  = 'Onion Rings',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'Crispy battered onion rings.',
},
['fsg_orange_juice'] = {
    label  = 'Orange Juice',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'Freshly squeezed orange juice.',
},
['fsg_pan_seared_steak'] = {
    label  = 'Pan-Seared Steak',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'A beautifully pan-seared steak.',
},
['fsg_pancakes'] = {
    label  = 'Pancakes',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'A stack of fluffy pancakes.',
},
['fsg_pasta_dish'] = {
    label  = 'Pasta Dish',
    weight = 450,
    stack  = true,
    close  = true,
    description = 'A classic pasta dish.',
},
['fsg_pepperoni_pizza'] = {
    label  = 'Pepperoni Pizza',
    weight = 550,
    stack  = true,
    close  = true,
    description = 'Wood-fired pepperoni pizza.',
},
['fsg_pepshrimp'] = {
    label  = 'Pepper Shrimp',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'Spicy pepper shrimp.',
},
['fsg_pineapple_juice'] = {
    label  = 'Pineapple Juice',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'Freshly pressed pineapple juice.',
},
['fsg_pineapple_pizza'] = {
    label  = 'Pineapple Pizza',
    weight = 550,
    stack  = true,
    close  = true,
    description = 'Wood-fired pizza with pineapple. Controversial.',
},
['fsg_popcorn'] = {
    label  = 'Popcorn',
    weight = 100,
    stack  = true,
    close  = true,
    description = 'A bag of freshly popped popcorn.',
},
['fsg_pulled_pork'] = {
    label  = 'Pulled Pork',
    weight = 500,
    stack  = true,
    close  = true,
    description = 'Slow-smoked pulled pork.',
},
['fsg_quesadilla'] = {
    label  = 'Quesadilla',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'A crispy cheese quesadilla.',
},
['fsg_quiche'] = {
    label  = 'Quiche',
    weight = 350,
    stack  = true,
    close  = true,
    description = 'A savoury baked quiche.',
},
['fsg_ramen'] = {
    label  = 'Ramen',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'A steaming bowl of ramen.',
},
['fsg_risotto'] = {
    label  = 'Risotto',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'Creamy Italian risotto.',
},
['fsg_salmon'] = {
    label  = 'Cooked Salmon',
    weight = 350,
    stack  = true,
    close  = true,
    description = 'Pan-cooked salmon fillet.',
},
['fsg_scrambled_eggs'] = {
    label  = 'Scrambled Eggs',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'Soft scrambled eggs.',
},
['fsg_smoothie'] = {
    label  = 'Smoothie',
    weight = 350,
    stack  = true,
    close  = true,
    description = 'A fresh blended smoothie.',
},
['fsg_soup'] = {
    label  = 'Soup',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'A bowl of soup.',
},
['fsg_spring_rolls'] = {
    label  = 'Spring Rolls',
    weight = 250,
    stack  = true,
    close  = true,
    description = 'Crispy fried spring rolls.',
},
['fsg_stir_fry'] = {
    label  = 'Stir Fry',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'Wok-fried vegetables and protein.',
},
['fsg_toast'] = {
    label  = 'Toast',
    weight = 100,
    stack  = true,
    close  = true,
    description = 'A slice of buttered toast.',
},
['fsg_tomato_juice'] = {
    label  = 'Tomato Juice',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'Freshly pressed tomato juice.',
},
['fsg_tv_dinner'] = {
    label  = 'TV Dinner',
    weight = 400,
    stack  = true,
    close  = true,
    description = 'A microwaved TV dinner.',
},
['fsg_waffle'] = {
    label  = 'Waffle',
    weight = 200,
    stack  = true,
    close  = true,
    description = 'A golden waffle.',
},
['fsg_watermelon_juice'] = {
    label  = 'Watermelon Juice',
    weight = 300,
    stack  = true,
    close  = true,
    description = 'Freshly pressed watermelon juice.',
},
